FROM openjdk:8

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID jenkins-agent
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID jenkins-agent

USER root

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh \
  && apt-get install -y git \
  && npm install -g -y yarn

USER jenkins-agent
