FROM openjdk:8

RUN apt-get update \
  && apt-get upgrade -y \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_12.x | bash - \
  && apt-get install -y nodejs \
  && curl -L https://www.npmjs.com/install.sh | sh \
  && apt-get install -y git \
  && npm install -g -y yarn
