openapi: 3.0.1
info:
  title: CP API Management API
  version: 1.7.0
  description: API Contract between strategic UI and CP API-Management
servers:
  - url: 'http://localhost:8080'
    description: Local
tags:
  - name: IO
    description: Input/Output endpoints
  - name: Settlement
    description: Settlement related endpoints
paths:
  /io:
    get:
      operationId: getIOList
      tags:
        - IO
      description: Fetch input output for scheme
      parameters:
        - $ref: '#/components/parameters/contextHeader'
        - $ref: '#/components/parameters/clientTypeHeader'
      responses:
        '200':
          description: Input output retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IODashboardDto'
        '400':
          description: Some of the request params are invalid
          content: {}
      summary: Get Input Outputs for scheme
  '/io-details/{participantId}':
    parameters:
      - name: participantId
        in: path
        description: participantId to display IO breakdown
        required: true
        schema:
          type: string
          example: NDEASESSXXX
    get:
      operationId: getIODetails
      tags:
        - IO
      description: Fetch input output data breakdown for a given participant
      parameters:
        - name: timestamp
          in: query
          description: timestamp
          schema:
            type: string
        - $ref: '#/components/parameters/contextHeader'
        - $ref: '#/components/parameters/clientTypeHeader'
      responses:
        '200':
          description: Input output retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IODashboardDto'
        '400':
          description: Some of the request params are invalid
          content: {}
      summary: Get Input Output details
  /settlement:
    get:
      operationId: getSettlements
      tags:
        - Settlement
      description: Fetch participants settlement positions broken down by previous and curreny cycles
      parameters:
        - name: fundingParticipantId
          in: query
          required: false
          description: Optional ID of a funding participant in order to filter by his funded participants. Omitting this parameter will make the endpoint return all top level participants at the scheme level. If the participantId does not have any funded participants - the response will have empty positions
          schema:
            type: string
            example: NDEASESSXXX
        - $ref: '#/components/parameters/contextHeader'
        - $ref: '#/components/parameters/clientTypeHeader'
      responses:
        '200':
          description: Settlement retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettlementDashboardDto'
        '400':
          description: Some of the request params are invalid
          content: {}
      summary: Get settlements
  '/settlementDetails/{participantId}':
    parameters:
      - name: participantId
        in: path
        description: Participant Id to get details for
        required: true
        schema:
          type: string
          example: NDEASESSXXX
    get:
      operationId: getSettlementDetails
      tags:
        - Settlement
      description: 'Fetch self funded Settlement, including positions, participant info and cycles'
      parameters:
        - $ref: '#/components/parameters/contextHeader'
        - $ref: '#/components/parameters/clientTypeHeader'
      responses:
        '200':
          description: Settlement retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ParticipantSettlementDetailsDto'
        '400':
          description: Some of the request params are invalid
          content: {}
      summary: Get settlement details by participant
components:
  parameters:
    contextHeader:
      name: context
      in: header
      required: true
      schema:
        type: string
        enum:
          - BPS
        example: BPS
      description: Context header to instruct the expected client
    clientTypeHeader:
      name: client-type
      in: header
      required: true
      schema:
        type: string
        enum:
          - UI
        example: UI
      description: Client type specification
  schemas:
    CycleDto:
      type: object
      title: CycleDto
      properties:
        cutOffTime:
          type: string
          format: date-time
          example: '2020-09-15T13:00:00Z'
        id:
          type: string
        settlementTime:
          type: string
          format: date-time
          example: '2020-09-15T13:00:00Z'
        status:
          type: string
          enum:
            - COMPLETED
            - NOT_STARTED
            - OPEN
    IOBatchesMessageTypesDto:
      title: IOBatchesMessageTypesDto
      type: object
      properties:
        code:
          type: string
        data:
          $ref: '#/components/schemas/IODataDetailsDto'
        name:
          type: string
    IODashboardDto:
      title: IODashboardDto
      type: object
      properties:
        batchesRejected:
          type: string
        dateFrom:
          type: string
          format: date
        filesRejected:
          type: string
        rows:
          type: array
          items:
            $ref: '#/components/schemas/ParticipantIODataDto'
        transactionsRejected:
          type: string
    IODataAmountDetailsDto:
      title: IODataAmountDetailsDto
      type: object
      properties:
        accepted:
          type: integer
          format: int32
        amountAccepted:
          type: integer
          format: int32
        amountOutput:
          type: integer
          format: int32
        output:
          type: integer
          format: int32
        rejected:
          type: number
          format: double
        submitted:
          type: integer
          format: int32
    IODataDetailsDto:
      title: IODataDetailsDto
      type: object
      properties:
        accepted:
          type: integer
          format: int32
        output:
          type: integer
          format: int32
        rejected:
          type: number
          format: double
        submitted:
          type: integer
          format: int32
    IODataDto:
      title: IODataDto
      type: object
      properties:
        rejected:
          type: number
          format: double
        submitted:
          type: integer
          format: int32
    IODetailsDto:
      title: IODetailsDto
      type: object
      properties:
        batches:
          type: array
          items:
            $ref: '#/components/schemas/IOBatchesMessageTypesDto'
        dateFrom:
          type: string
          format: date
        files:
          $ref: '#/components/schemas/IODataDetailsDto'
        participant:
          $ref: '#/components/schemas/ParticipantDto'
        transactions:
          type: array
          items:
            $ref: '#/components/schemas/IOTransactionsMessageTypesDto'
    IOTransactionsMessageTypesDto:
      title: IOTransactionsMessageTypesDto
      type: object
      properties:
        code:
          type: string
        data:
          $ref: '#/components/schemas/IODataAmountDetailsDto'
        name:
          type: string
    IntraDayPositionGrossDto:
      title: IntraDayPositionGrossDto
      type: object
      properties:
        debitCap:
          type: number
        debitPosition:
          type: number
    Participant:
      title: Participant
      type: object
      properties:
        bic:
          type: string
        fundingBic:
          type: string
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum:
            - ACTIVE
            - SUSPENDED
        suspendedTime:
          type: string
          format: date-time
          example: '2020-09-15T13:00:00Z'
    ParticipantDto:
      title: ParticipantDto
      type: object
      properties:
        bic:
          type: string
        fundingBic:
          type: string
        id:
          type: string
        name:
          type: string
        status:
          type: string
          enum:
            - ACTIVE
            - SUSPENDED
        suspendedTime:
          type: string
          format: date-time
          example: '2020-09-15T13:00:00Z'
    ParticipantIODataDto:
      title: ParticipantIODataDto
      type: object
      properties:
        batches:
          $ref: '#/components/schemas/IODataDto'
        files:
          $ref: '#/components/schemas/IODataDto'
        participant:
          $ref: '#/components/schemas/ParticipantDto'
        transactions:
          $ref: '#/components/schemas/IODataDto'
    ParticipantPositionDto:
      title: ParticipantPositionDto
      type: object
      properties:
        credit:
          type: integer
          format: int64
        debit:
          type: integer
          format: int64
        netPosition:
          type: integer
          format: int64
    ParticipantSettlementDetailsDto:
      title: ParticipantSettlementDetailsDto
      type: object
      properties:
        currentCycle:
          $ref: '#/components/schemas/CycleDto'
        currentPosition:
          $ref: '#/components/schemas/PositionDetailsDto'
        currentPositionTotals:
          $ref: '#/components/schemas/PositionDetailsTotalsDto'
        intraDayPositionGross:
          $ref: '#/components/schemas/IntraDayPositionGrossDto'
        participant:
          $ref: '#/components/schemas/ParticipantDto'
        previousCycle:
          $ref: '#/components/schemas/CycleDto'
        previousPosition:
          $ref: '#/components/schemas/PositionDetailsDto'
        previousPositionTotals:
          $ref: '#/components/schemas/PositionDetailsTotalsDto'
        settlementBank:
          $ref: '#/components/schemas/ParticipantDto'
    PositionDetailsDto:
      title: PositionDetailsDto
      type: object
      properties:
        customerCreditTransfer:
          $ref: '#/components/schemas/ParticipantPositionDto'
        paymentReturn:
          $ref: '#/components/schemas/ParticipantPositionDto'
    PositionDetailsTotalsDto:
      title: PositionDetailsTotalsDto
      type: object
      properties:
        totalCredit:
          type: integer
          format: int64
        totalDebit:
          type: integer
          format: int64
        totalNetPosition:
          type: integer
          format: int64
    SettlementDashboardDto:
      title: SettlementDashboardDto
      type: object
      properties:
        currentCycle:
          $ref: '#/components/schemas/CycleDto'
        positions:
          type: array
          items:
            $ref: '#/components/schemas/TotalPositionDto'
        previousCycle:
          $ref: '#/components/schemas/CycleDto'
    TotalPositionDto:
      title: TotalPositionDto
      type: object
      properties:
        currentPosition:
          $ref: '#/components/schemas/ParticipantPositionDto'
        participant:
          $ref: '#/components/schemas/Participant'
        previousPosition:
          $ref: '#/components/schemas/ParticipantPositionDto'
