bps-config:
  retryCount: 3
  timeoutDuration: 5000
  schemeCode: P27-SEK
  ioDetailsThreshold: 2

  currencies:
    P27-SEK: SEK

  base-urls:
    MOCK: http://localhost:9999/positions-mock-server
    BPS: http://snow-den:0909/

  paths:
    intra-day-position-gross-path:
      path: /settlement/runningDebitCapPosition/readAll
      base: MOCK
    settlement-position-path:
      path: /settlement/runningSettlementPosition/readAll
      base: MOCK
    participants-path:
      path: /participants/{schemeCode}/readAll
      base: MOCK
    participant-path:
      path: /participants/{schemeCode}/read
      base: MOCK
    managed-participant-path:
      path: /participants/managed
      base: MOCK
    cycles-path:
      path: /cycles/readAll
      base: MOCK
    day-cycles-path:
      path: /cycles/read
      base: MOCK
    file-enquiries-path:
      path: /enquiries/file/{schemeCode}/readAll
      base: MOCK
    io-participants-path:
      path: /schemeIO/{schemeCode}/readAll
      base: MOCK
    io-details-path:
      path: /schemeIO/participant/{schemeCode}/read
      base: MOCK
    alerts-path:
      path: /alerts
      base: MOCK
    message-direction-references-path:
      path: /reference/messages
      base: MOCK
    alert-threshold-path:
      path: /reference/alerts
      base: MOCK
    alert-stats-path:
      path: /alerts/stats
      base: MOCK
    reason-codes-path:
      path: /reference/reasonCode/{schemeCode}/readAll
      base: MOCK
    statuses-path:
      path: /reference/status/{schemeCode}/{level}/readAll
      base: MOCK
    batch-enquiries-path:
      path: /enquiries/batches/{schemeCode}/readAll
      base: MOCK
    single-file-path:
      path: /enquiries/file/{schemeCode}/read
      base: MOCK
    download-file-path:
      path: /enquiries/file/downloadFile/{schemeCode}
      base: MOCK
    single-batch-path:
      path: /enquiries/batches/{schemeCode}/read
      base: MOCK
    settlement-details-path:
      path: /enquiries/settlement/enquiry/{schemeCode}/read
      base: MOCK
    instruction-enquiries-path:
      path: /enquiry/instructions
      base: MOCK
    settlement-enquiries-path:
      path: /enquiries/settlement/enquiry/{schemeCode}/readAll
      base: MOCK
    settlement-schedule-path:
      path: /enquiries/settlement/schedule/{schemeCode}/readAll
      base: MOCK
    transaction-enquiries-path:
      path: /enquiries/transactions/{schemeCode}/readAll
      base: MOCK
    single-transaction-path:
      path: /enquiries/transactions/{schemeCode}/read
      base: MOCK
    single-account-path:
      path: /account/read
      base: MOCK
    approval-details-path:
      path: /approvals/{schemeCode}/read
      base: MOCK
    approval-create-path:
      path: /approvals/{schemeCode}
      base: MOCK
    approvals-path:
      path: /approvals/{schemeCode}/readAll
      base: MOCK
    broadcasts-path:
      path: /broadcasts/readAll
      base: MOCK
    broadcasts-create-path:
      path: /broadcasts
      base: MOCK
    participant-configuration-path:
      path: /participants/{schemeCode}/configuration
      base: MOCK
    routing-record-path:
      path: /routing/{schemeCode}/records
      base: MOCK
    reports-path:
      path: /reports
      base: MOCK
    download-report-path:
      path: /reports/downloadFile/{schemeCode}
      base: MOCK
    approval-request-by-path:
      path: /reference/approvals/requestedBy/{schemeCode}/readAll
      base: MOCK
    approval-request-type-path:
      path: /reference/approvals/requestTypes/{schemeCode}/readAll
      base: MOCK

  retryable: 404, 429

  eod-period:
    start: "18:00"
    end: "19:00"
